name: Ubuntu CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      matrix:
        jdkversion: [11]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'maven'
    - name: Build with Maven
      run: /usr/actions-runner/apache-maven-3.9.1/bin/mvn -V -B clean package --file pom.xml
