name: AutoBuilder

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      matrix:
        jdkversion: [11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'maven'
    - name: 使用Maven构建
      run: mvn -V -B clean package --file pom.xml
    - name: 上传文件
      uses: actions/upload-artifact@v1
      with:
        name: 生成的文件
        path: ${{ github.workspace }}/target/AuthMe-5.6.0-FORK.jar
      
